# Generated by Django 4.1.1 on 2022-10-08 15:32

from django.db import migrations


def migrate_fk_to_m2m(apps, schema_migration):
    Blog = apps.get_model('blog', 'Blog')

    for blog in Blog.objects.all():
        if blog.author:
            blog.contributors.add(
                blog.author,
                through_defaults={'contribution': 'Main author'}
            )


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_author_blogcontributor_blog_contributors"),
    ]

    operations = [
        migrations.RunPython(migrate_fk_to_m2m)
    ]
