# Generated by Django 4.1.1 on 2022-10-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_auto_20221008_1532"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="author",
        ),
    ]
