# Generated by Django 4.1.1 on 2022-10-05 22:09

from django.db import migrations


def create_groups(apps, schema_migration):
    User = apps.get_model('authentication', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_blog = Permission.objects.get(codename='add_blog')
    change_blog = Permission.objects.get(codename='change_blog')
    delete_blog = Permission.objects.get(codename='delete_blog')
    view_blog = Permission.objects.get(codename='view_blog')

    creator_permissions = [
        add_blog,
        change_blog,
        delete_blog,
        view_blog,
    ]

    creators = Group(name='creators')
    creators.save()
    creators.permissions.set(creator_permissions)

    subscribers = Group(name='subscribers')
    subscribers.save()
    subscribers.permissions.add(view_blog)

    for user in User.objects.all():
        if user.role == 'CREATOR':
            creators.user_set.add(user)
        elif user.role == 'SUBSCRIBER':
            subscribers.user_set.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_profile_photo_alter_user_role"),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
